[book]
title = "Getting Started with Embedded Rust on Pico"
#authors = ["Tiago Manczak", "Michael Schury"]
multilingual = false
src = "src"
language = "en"

[output.html.playground]
editable = true

# Create PDF with toc
# [output.html]
# [output.pdf]
# [output.pdf-outline]
# PDF-File: ./book/pdf-outline/output.pdf